### ISSUE TITLE
Weak PRNG used

### ISSUE THREAD

**Issue by paragonie-scott** [stormpath/stormpath-sdk-php#132]
Insecure RNG: https://github.com/stormpath/stormpath-sdk-php/blob/15aee3007b8aa41c20cdf28fd650b8a2368a7fa9/src/Util/UUID.php#L167-L181

Insecure RNG fallback: https://github.com/stormpath/stormpath-sdk-php/blob/62698ea98ef89217f932e28cf3e511d39af3b4cf/src/Authc/Api/ApiKeyEncryptionOptions.php#L48-L50

Background: https://paragonie.com/blog/2015/07/how-safely-generate-random-strings-and-integers-in-php

Might I recommend https://github.com/paragonie/random_compat instead?

**Comment by bretterer** [comment]
Thank you for your feedback.  

Currently, we are going to keep it the way it is. The reason for this, we have tried to use CSPRNG's in the past but do not work for every application.  Our goal here is to give everyone the ability to use our product and using '/dev/urandom' does not work for everyone and can also slow the system down a lot.

The way we generate our UUID's is not actually the method you are showing here.  We generate our UUID's with the method found here. https://github.com/stormpath/stormpath-sdk-php/blob/15aee3007b8aa41c20cdf28fd650b8a2368a7fa9/src/Util/UUID.php#L351-L372   This is still using mt_rand but is ok with us.

**Comment by paragonie-scott** [comment]
> The reason for this, we have tried to use CSPRNG's in the past but do not work for every application.  Our goal here is to give everyone the ability to use our product and using '/dev/urandom' does not work for everyone

For balance, random_compat is used by WordPress (as of 4.4) and currently works cross-platform even on ancient versions of PHP. It will almost certainly work for your users (as you require PHP 5.4+).

> and can also slow the system down a lot

I think you're thinking of `/dev/random` not `/dev/urandom`? I've [benchmarked `mt_rand()` vs CSPRNGs](https://gist.github.com/sarciszewski/f7bd4c0358a44321787b) previously. (OpenSSL is the fastest, but it's a userspace CSPRNG that shares state across forks, which caused collisions in `ramsey/uuid` and other libraries.)

> This is still using mt_rand but is ok with us.

![c4jt321](https://cloud.githubusercontent.com/assets/11591518/13093743/ed9068d8-d4d4-11e5-877d-fa86b68761b6.png)

**Comment by TomMD** [comment]
Scary to say the least.  It's rather easy to make a generator that draws entropy from `/dev/urandom` (OS X, *nix) or CryptAPI (Windows).  Would that suffice or are there more platforms you are referring to?

**Comment by bretterer** [comment]
@paragonie-scott,

Sorry, I hit the `X` instead of the edit on my Github comment and didn't mean to.

You are correct, I was thinking `/dev/random` in my comment.  I understand that `/dev/urandom` is being used in WordPress.  Use of `/dev/urandom` does follow current best practice for generating random numbers.  At this time however, we do not have this in our backlog to change out in the PHP SDK but will make sure we put this on our priority list to investigate. 

When we create packages for developers to use, we try to use built in php functions and limit the number of external packages we require during the installation of the package. This is the main reason why we initially used built in methods.  



> Here is the orig comment for reference:

> The reason for this, we have tried to use CSPRNG's in the past but do not work for every application. Our goal here is to give everyone the ability to use our product and using '/dev/urandom' does not work for everyone and can also slow the system down a lot.
> This is still using mt_rand but is ok with us.

**Comment by paragonie-scott** [comment]
> When we create packages for developers to use, we try to use built in php functions and limit the number of external packages we require during the installation of the package. This is the main reason why we initially used built in methods. 

Luckily, random_compat is a polyfill for the new internal functions in PHP 7.

* https://secure.php.net/random_bytes
* https://secure.php.net/random_int

In PHP 7, including the library is a NOP. In PHP 5, it uses the most secure backend available.

**Comment by bretterer** [comment]
@paragonie-scott so for a little bit of information on how we currently use the `UUID::v4()` method in our system. This is used inside of our `Stormpath\Resource\Application` resource during our creation of the ID Site URL generation. In our JWT, we define a `jti` which is a random number.  This does not require a cryptographically secure values which is why we are still using `mt_rand()` function inside of PHP. 

As I said before, We are happy to look at these suggestions of changing our current `UUID::v4` method to use a different method of generating random numbers.  I will leave this ticket open until we discuss this internally at more depth.

**Comment by paragonie-scott** [comment]
For what it's worth: https://paragonie.com/blog/2015/07/common-uses-for-csprngs-cryptographically-secure-pseudo-random-number-generators#uuid-v4

**Comment by AshleyPinner** [comment]
> Use of /dev/urandom does follow current best practice for generating random numbers.

Say's who?

For reference, urandom is what you want: http://sockpuppet.org/blog/2014/02/25/safely-generate-random-numbers/

**Comment by atoponce** [comment]
>> Use of /dev/urandom does follow current best practice for generating random numbers.

> Say's who?

As you linked to, if you have access to a kernelspace CSPRNG, whether through an API, or accessing the device directly, you should use it, instead of relying on a userspace CSPRNG, unless you know you need otherwise. Chances are high that the system CSPRNG has already been correctly seeded with sufficient entropy, and it's output is indistinguishable from true random.

**Comment by AshleyPinner** [comment]
Herp. For some reason pre-coffee I misread that as "Use of /dev/urandom doesn't follow..."

Ignore me!

**Comment by bretterer** [comment]
Thank you again for reporting this.  We have removed the weak PRNG from our API Key Options file as it was dead code.  Since the PHP SDK requires PHP 5.4 and above, there is never a case where openssl_random_pseudo_bytes would not be available.

**Comment by paragonie-scott** [comment]
Please be aware that [OpenSSL's userspace PRNG isn't fork-safe](https://github.com/ramsey/uuid/issues/80).

**Comment by bretterer** [comment]
@paragonie-scott, Thank you for mentioning this.  After discussing this with our internal team, I would like to re-visit this.  Could you please email me, brian@stormpath.com.  I would like to discuss your package you mentioned here a little bit more.
