### ISSUE TITLE
Travis CI Fails when running multiple tests at once

### ISSUE THREAD

**Issue by bretterer** [stormpath/stormpath-sdk-php#86]
We need to fix this to allow for multiple test environments to be run at the same time.

**Comment by dogeared** [comment]
@bretterer - I've been working on something for the tests in the JSDK where any resource in Stormpath that is created has a prefix in the name - per test.

Any verification queries in the tests make use of the prefix so that only the objects relevant to that particular test are used (and later, cleaned up).

This way, multiple tests could be run against the same tenant.
